---
title: "modeling"
author: "Bruce"
date: "August 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
rm(list = ls())
```
#加载类
```{r}
library(recommenderlab)
data <- read.csv('/home/bruce/gitdir/R/competition/data_cleansing.csv',stringsAsFactors = F,row.names = 1)

```

调换两个列的序列
```{r}
data_ip <- data$ip
data_page_path <- data$page_path
data[,1] <-data_ip
data[,2] <-data_page_path
colnames(data) <- c("ip","page_path")
```
转换为一个二进制的矩阵，然后创建一个模型
```{r}
data1 <- as(data,'binaryRatingMatrix')
mode <- Recommender(data1,method = 'POPULAR')#contribute a model
```
根据每个用户来预测。
```{r}
pre <- predict(mode,data1,n= 5 ,type='topN')
pre1 <- as(pre,'list')
```
下面是交叉验证
```{r}
eva_s <- evaluationScheme(data1, method="cross-validation", k=10, given = 1)
```

```{r}
algorithms <- list(popular = list(name = "POPULAR", param = NULL),
ubcf = list(name = "UBCF", param = NULL), ibcf = list(name = "IBCF", param = NULL))
```
```{r}
eva <-evaluate(eva_s,algorithms,type='topNList',n=1:10)
```
```{r}
plot(eva,annotate= 1:3,legend="topleft")
plot(eva,"prec/rec",annotate= 1:3)
```

