---
title: "pre_handle"
author: "Bruce"
date: "August 7, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(DBI)
library(RMySQL)
con <- dbConnect(MySQL(), host='127.0.0.1',port=3306,
                 dbname='test', user='root', password='qertu1014')
dbSendQuery(con,'set character_set_results=gbk')
dbSendQuery(con,'set character_set_connection = gbk')
dbSendQuery(con,'set character_set_database =gbk')
dbSendQuery(con,'set character_set_client =gbk')
temp<-dbSendQuery(con,'select * from all_gzdata')
data <- dbFetch(temp, n=-1)
dbDisconnect(con)
my_data <- data[grep('107',data$fullURLId),]
```
1	??????realIP?????????fullURL??????
```{r}
data<-my_data[,c("realIP",'fullURL')]
```

2	?????¤ç????????ï¼????????????¢ç????¨å??
```{r}
data$fullURL <- gsub("\\?*",'',data$fullURL)
```

3	?????¤ä????????.html??????ç½????
```{r}
data<-data[grep('\\.html',data$fullURL),]
#rm(data1)
```

4	??¾å?ºå¸¦ç¿»é¡µ???ç½????
```{r}
data$fullURL<-gsub("_\\d+",'',data$fullURL)
```

5	å°?ç¿»é¡µç½????è¿????
6	ç­??????ºå??å§»ç±»ç½????
```{r}
hdata<-data[grep('hunyin',data$fullURL),]
```
??????.html?????¢æ??å­?æ¯????ç½?é¡?
```{r}
#hdata<-huiyin_web[grep()]
```

7	??»é??
```{r}
hdata<- unique(hdata)
```

8	ç­????æµ?è§?è®°å??2æ¬¡ä»¥ä¸????IP
```{r}
h <- table(hdata$realIP)
Ip<-names(h[h>2])
h>2
```
ip is for >2 times.not the total data
9	å°???°æ????????ä¸ºæ??è¯????ä¸?è®?ç»????
```{r}
set.seed(1234)
index4 <- sample(1:2,length(Ip),replace = T, prob = c(0.8,0.2))
trainIp <- Ip[index4==1]
testIp<- Ip[index4==2]
```

```{r}
train_data <- hdata[hdata$realIP %in% trainIp,]
test_data <- hdata[hdata$realIP %in% testIp,]
```
write in the directory
```{r}
write.csv(train_data,file = 'train_data.csv')
write.csv(test_data,file = 'test_data.csv')
```

10	???å»ºç?¨æ?·æ??è§???©é??
11	??¹æ????°å?¡å¾·ç³»æ?°å??å¼?????????©å????¸ä¼¼åº???©é??
12	???å»ºå??è¡?ï¼?æ¯?ä¸?IP???æµ?è§?è®°å??ä¸ºä??ä¸?å­?è¡?
13	??©ç?¨æ??è¯????ï¼???¹æ????¨æ?·ç??ç¬?ä¸???¡æ??è§?è®°å??è¿?è¡???¨è??
14	è®¡ç????¨è??æ­£ç¡®???
```{r}

```
```{r}

```

