---
title: "medical"
author: "Bruce"
date: "August 6, 2017"
output: html_document
---

```{r}
data<- read.csv("/home/bruce/Desktop/data_exercise/data.csv");data
```

coefficient
we can use a loop to implement
```{r}
for(i in 1:nrow(data)){
  ran<- c()
  if(data[i,1]<=0.15){
    append(ran,"B1")
  }else if(data[i,1]<=0.296){
    append(ran,"B4")
  }else if(data[i,1]<=0.485){
    append(ran,"B2")
  }else if(data[i,1]<=0.78)
  {
    append(ran,"B3")
  }
}
```
范围标识  热毒蕴结证型系数范围	范围内元素的个数

   B1	      [0,0.15]	           325

   B2	      [0.297,0.485]	   180

   B3	      [0.494,0.78]	    29

   B4	      [0.151,0.296]	   396
```{r}
data[which(data[,2]>=0&data[,2]<=0.15),1]<-"B1"
data[which(data[,2]>=0.151&data[,2]<=0.296),2]<-"B4"
data[which(data[,2]>=0.297&data[,2]<=0.485),1]<-"B2"
data[which(data[,2]>=0.494&data[,2]<=0.78),1]<-"B3"
```

```{r}
data[which(data[,1]>=0&data[,1]<=0.179),1]<-"A1"
data[which(data[,1]>=0.18&data[,1]<=0.258),1]<-"A3"
data[which(data[,1]>=0.259&data[,1]<=0.35),1]<-"A4"
data[which(data[,1]>=0.354&data[,1]<=0.504),1]<-"A2"
```
范围标识  冲任失调证型系数范围	范围内元素的个数

   C1	      [0.438,0.61]	   35

   C2	      [0.289,0.415]	   206

   C3	      [0.067,0.201]	   296

   C4	      [0.202,0.288]	   393
```{r}
data[which(data[,3]>=0.354&data[,3]<=0.504),1]<-"A2"
```
```{r}

```

